config/routes.rb
Rails.application.routes.draw do
  
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Plutus::Engine => "/plutus", :as => "plutus"
  
  # devise_for :members, :controllers => {:registrations => "admin/members"}
  devise_for :users,  :controllers => {:registrations => "admin/users"}
  

  devise_scope :user do
    get    'users' => 'admin/users#index', as: :users
    get    'user/:id' => 'admin/users#show', as: :user_profile
    get    'staff_tracking' => 'admin/users#staff_tracking', as: :staff_tracking
    get    'users/:id/edit' => 'admin/users#edit', as: :edit_user
    patch  'users/:id' =>               'admin/users#update'
    get    'change_role/:id/edit'  =>  'admin/users#change_role', as: :update_staff_role
    patch  'change_role/:id'  =>     'admin/users#update_role'
  end

  get    'members' => 'admin/members#index', as: :members
  get    'member/:id' => 'admin/members#show', as: :member_profile
  get    'renew_member/:id' => 'admin/members#renew_membership', as: :renew_member
  get    'unsubscribe_member/:id' => 'admin/members#unsubscribe_membership', as: :unsubscribe_member
  put    'cash_renewal/:id' => 'admin/members#cash_renewal', as: :cash_renewal
  put    'pos_renewal/:id' => 'admin/members#pos_renewal', as: :pos_renewal
  post   'paystack_renewal' => 'admin/members#paystack_renewal', as: :paystack_renewal
  post   'pause_subscription' => 'admin/members#pause_subscription', as: :pause_subscription
  post   'cancel_pause' => 'admin/members#cancel_pause', as: :cancel_pause
  get    'fund_wallet/:id' => 'admin/wallets#fund_page', as: :wallet_fund_page
  post   'paystack_wallet_fund' => 'admin/wallets#paystack_wallet_fund', as: :paystack_wallet_fund
  post   'wallet_renewal' => 'admin/members#wallet_renewal', as: :wallet_renewal
  put    'pos_wallet_fund/:id' => 'admin/wallets#pos_wallet_fund', as: :pos_wallet_fund
  put    'cash_wallet_fund/:id' => 'admin/wallets#cash_wallet_fund', as: :cash_wallet_fund
  get    'subscription_history/:id' => 'admin/historicals#subscription_history', as: :member_subscription_history
  get    'loyalty_history/:id' => 'admin/historicals#loyalty_history', as: :member_loyalty_history
  get    'wallet_history/:id' => 'admin/historicals#wallet_history', as: :member_wallet_history
  get    'attendance_history/:id' => 'admin/historicals#attendance_history', as: :member_attendance_history
  get    'members/:id/edit' => 'admin/members#edit', as: :edit_member
  patch  'members/:id' => 'admin/members#update'
  get    'members/new' => 'admin/members#new', as: :new_member
  post   'members'     => 'admin/members#create'
  get    'members/:id'  => 'admin/members#image_capture', as: :image_page
  post   'members/upload_image' => 'admin/members#upload_image', as: :image_upload
  get    'members/activate_account/:id' => 'admin/members#activate_account', as: :activate_account
  patch  'members/activate_account/:id' => 'admin/members#complete_activation'
  get    'members/change_plan/:id' => 'admin/members#change_plan', as: :change_plan
  post   'send_paystack_invoice' => 'admin/members#send_paystack_invoice', as: :send_paystack_invoice
  patch  'members/change_plan/:id' => 'admin/members#change_plan_update'


  namespace :admin do
    resources :attendance_records, only: [:index]
    resources :subscription_plans
    resources :features
    resources :fitness_goals
    resources :payment_methods
    resources :member_steps
    resources :health_conditions
    post  'paystack_subscribe' => 'member_steps#paystack_subscribe', as: :paystack_subscription
    post  'upload_image' => 'member_steps#upload_image', as: :image_upload
    post  'member_check_in' => 'attendance_records#member_check_in', as: :member_check_in
    get   'developer_test_mail_form' => 'developer_test#get_mail_form', as: :get_mail_form
    patch 'developer_test_email' => 'developer_test#send_mail', as: :developer_send_mail
    post  'check_recurring' => 'subscription_plans#check_recurring', as: :check_recurring
    post  'check_selected_plan' => 'subscription_plans#check_selected_plan', as: :check_selected_plan
    resources :loyalties
    resources :one_off_revenues
  end

  post '/:paystack_webhook' => 'webhooks#receive', as: :receive_webhooks

  root 'welcome#index'

  get 'welcome/index'

end

app/models/attendance_record.rb
class AttendanceRecord < ApplicationRecord
    
    audited associated_with: :member

    enum membership_status: [:active, :deactivated, :paused]
    
    belongs_to :member

    
end

app/controllers/admin/attendance_records_controller.rb
class Admin::AttendanceRecordsController < ApplicationController
    
    before_action :authenticate_user!
    before_action :find_member, only: [:member_check_in, :create_attendance_record, :check_visitation_count, :check_in_process]


    def index
        @filterrific = initialize_filterrific(
          Member.with_account_details,
            params[:filterrific],
            select_options: {
              with_subscription_plan_id: SubscriptionPlan.options_for_select,
              with_fitness_goal_id: FitnessGoal.options_for_select,
              with_payment_method_id: PaymentMethod.options_for_select,
              sorted_by: Member.options_for_sorted_by
            },
            persistence_id: 'shared_key',
            default_filter_params: {},
        ) or return
        @members = @filterrific.find.page(params[:page]).per_page(15)
            
        respond_to do |format|
          format.html
          format.js
        end
    
        rescue ActiveRecord::RecordNotFound => e
          puts "Had to reset filterrific params: #{ e.message }"
          redirect_to(reset_filterrific_url(format: :html)) && return
      end


    def member_check_in
        if @member.account_detail.gym_attendance_status != 'checkedin'
            member_visitation_count = @member.account_detail.visitation_count
            plan_allowed_visitation = @member.subscription_plan.allowed_visitation_count
            if @member.account_detail.member_status == 'active' && plan_allowed_visitation == 'unlimited'
                check_in_process
            elsif @member.account_detail.member_status == 'active' &&  plan_allowed_visitation != 'unlimited' && member_visitation_count.to_i < plan_allowed_visitation.to_i
                check_in_process
            elsif @member.account_detail.member_status == 'active' &&  plan_allowed_visitation != 'unlimited' && member_visitation_count.to_i >= plan_allowed_visitation.to_i
                render status: 200, json: {
                    message: "exhausted"
                }
            else
                render status: 200, json: {
                    message: "failed"
                }
            end
        else 
            render status: 200, json: {
                message: "checkedin"
            }
        end
    end



    private

    def find_member
        @member = Member.find(params[:id]) 
    end


    def create_attendance_record
        @member.attendance_records.create(
            checkin_date: DateTime.now,
            checkout_date: nil,
            membership_status: @member.account_detail.member_status,
            membership_plan: @member.subscription_plan.plan_name,
            staff_on_duty: current_user.fullname,
            audit_comment: "checked into the gym" )
    end
    
    def check_visitation_count
        @member.visitation_count
    end

    def check_in_process
        create_attendance_record
        @member.account_detail.gym_attendance_status = 1
        @member.account_detail.visitation_count +=1
        @member.save
        render status: 201, json: {
            message: "success"
        }
    end


end

app/helpers/admin/attendance_records_helper.rb
module Admin::AttendanceRecordsHelper
end

app/views/admin/attendance_records/_list.html.erb
<div class="col-12" id="filterrific_results_check_in">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Member List</h4>
            <div id="check_in_message"></div>
            <h6 class="card-subtitle"></h6>
            <div class="table-responsive">
                <table class="table m-t-30 table-hover contact-list" data-page-size="10" id="table_check_in[{{id}}]">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Customer Code
                            <th>First Name</th>
                            <th>Last Name </th>
                            <th>Plan </th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    <% members.each do |member| %>
                        <tr>
                            <td><%= member.id %></td>
                            <td><%= member.customer_code %></td>
                            <% if member.image_data.nil? %>
                                <td>
                                    <%= image_tag( "users/5.png", alt: "member", size:"40", class:"img-circle" ) %><%= link_to "#{member.first_name}", member_profile_path(member) %>
                                </td>
                            <% else %>
                                <td>
                                    <%= image_tag( "#{member.image_url}", alt: "member", size:'40', class:"img-circle" ) %><%= link_to "#{member.first_name}", member_profile_path(member) %>
                                </td>
                            <% end %>
                            <td><%= member.last_name %></td>
                            <td><span><%= member.subscription_plan.plan_name %><span></td>
                            <% if member.account_detail.member_status == "active" %>
                                <td><span class="label label-success"><%= member.account_detail.member_status.titleize %></span> </td>
                            <% else %>
                                <td><span class="label label-danger"><%= member.account_detail.member_status.titleize %></span> </td>
                            <% end %>
                            <td>
                                <% if member.account_detail.gym_attendance_status == 'checkedin' %>
                                    <button id="" class="check_in_button btn btn-danger" href="#" data-id="<%= member.id %>" data-value="<%= member.id%>">Checked In</button>
                                <% else %>
                                    <button id="" class="check_in_button btn btn-info" href="#" data-id="<%= member.id %>" data-value="<%= member.id%>">Check In</button>
                                <% end %>
                            </td>                    
                        </tr>
                    <% end %>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2">
                                <%= link_to "Add New Member", new_member_path, class:"btn btn-info btn-rounded" %>                                                   
                            </td>                                               
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <td colspan="7">
                                <div class="text-right">
                                    <ul class="pagination"> 
                                        <%= will_paginate members, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/admin/attendance_records/index.html.erb
        
        <div class="page-wrapper">
                    <!-- ============================================================== -->
                    <!-- Bread crumb and right sidebar toggle -->
                    <!-- ============================================================== -->
                    <div class="row page-titles">
                        <div class="col-md-5 align-self-center">
                            <h3 class="text-themecolor">Check In Members</h3>
                        </div>
                        <div class="col-md-7 align-self-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                <li class="breadcrumb-item">Member</li>
                                <li class="breadcrumb-item active">Attendance Check In</li>
                            </ol>
                        </div>
                        <div>
                            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                        </div>
                    </div>
                    <!-- ============================================================== -->
                    <!-- End Bread crumb and right sidebar toggle -->
                    <!-- ============================================================== -->
                    <!-- ============================================================== -->
                    <!-- Container fluid  -->
                    <!-- ============================================================== -->
                    <div class="container-fluid">
                        <!-- ============================================================== -->
                        <!-- Start Page Content -->
                        <!-- ============================================================== -->
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <% if flash[:error] %>
                                            <div class="alert alert-danger">
                                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                                <%= flash[:notice] %>
                                            </div>
                                        <% elsif flash[:notice] %>
                                            <div class="alert alert-success">
                                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                                <%= flash[:notice] %>
                                            </div>
                                        <% end %>                                        
                                        <h4 class="card-title">Search Members</h4>
                                        <div id="education_fields"></div>
                                        <%= form_for_filterrific @filterrific, html: {class: 'form-group m-t-40' } do |f| %>
                                            <div class="row">
                                                <div class="col-sm-3 nopadding">
                                                    <div class="form-group">
                                                        <%= f.text_field(:search_query, class: 'filterrific-periodically-observed form-control', placeholder: 'Code or Phone number') %>
                                                    </div>
                                                </div>
                                                <div class="col-sm-3 nopadding">
                                                     <div class="form-group">
                                                        <%= f.text_field(:search_names, class: 'filterrific-periodically-observed form-control', placeholder: 'First or Last Name') %>
                                                    </div>                                             
                                                </div>
                                                <div class="col-sm-3 nopadding">
                                                    <div class="form-group">
                                                        <%= f.select( :with_subscription_plan_id, @filterrific.select_options[:with_subscription_plan_id], { include_blank: 'Subscription Plans' }, class: 'form-control') %>
                                                    </div>
                                                </div>
                                                <div class="col-sm-3 nopadding">
                                                    <div class="form-group">
                                                         <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], { include_blank: ' ' }, class: 'form-control') %>
                                                    </div>
                                                </div>
                                                <div class="col-sm-3" >
                                                    <%= link_to('Reset filters', reset_filterrific_url) %> |  <%= render_filterrific_spinner %> 
                                                   
                                                </div>
                                            </div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <%= render(partial: 'admin/attendance_records/list', locals: { members: @members } ) %>
                        </div>
                    </div>

app/views/admin/attendance_records/index.js.erb
<% js = escape_javascript(
  render(partial: 'admin/attendance_records/list', locals: { members: @members })
  )
%>

$("#filterrific_results_check_in").html("<%= js %>");