config/routes.rb
Rails.application.routes.draw do
  
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Plutus::Engine => "/plutus", :as => "plutus"
  
  # devise_for :members, :controllers => {:registrations => "admin/members"}
  devise_for :users,  :controllers => {:registrations => "admin/users"}
  

  devise_scope :user do
    get    'users' => 'admin/users#index', as: :users
    get    'user/:id' => 'admin/users#show', as: :user_profile
    get    'staff_tracking' => 'admin/users#staff_tracking', as: :staff_tracking
    get    'users/:id/edit' => 'admin/users#edit', as: :edit_user
    patch  'users/:id' =>               'admin/users#update'
    get    'change_role/:id/edit'  =>  'admin/users#change_role', as: :update_staff_role
    patch  'change_role/:id'  =>     'admin/users#update_role'
  end

  get    'members' => 'admin/members#index', as: :members
  get    'member/:id' => 'admin/members#show', as: :member_profile
  get    'renew_member/:id' => 'admin/members#renew_membership', as: :renew_member
  get    'unsubscribe_member/:id' => 'admin/members#unsubscribe_membership', as: :unsubscribe_member
  put    'cash_renewal/:id' => 'admin/members#cash_renewal', as: :cash_renewal
  put    'pos_renewal/:id' => 'admin/members#pos_renewal', as: :pos_renewal
  post   'paystack_renewal' => 'admin/members#paystack_renewal', as: :paystack_renewal
  post   'pause_subscription' => 'admin/members#pause_subscription', as: :pause_subscription
  post   'cancel_pause' => 'admin/members#cancel_pause', as: :cancel_pause
  get    'fund_wallet/:id' => 'admin/wallets#fund_page', as: :wallet_fund_page
  post   'paystack_wallet_fund' => 'admin/wallets#paystack_wallet_fund', as: :paystack_wallet_fund
  post   'wallet_renewal' => 'admin/members#wallet_renewal', as: :wallet_renewal
  put    'pos_wallet_fund/:id' => 'admin/wallets#pos_wallet_fund', as: :pos_wallet_fund
  put    'cash_wallet_fund/:id' => 'admin/wallets#cash_wallet_fund', as: :cash_wallet_fund
  get    'subscription_history/:id' => 'admin/historicals#subscription_history', as: :member_subscription_history
  get    'loyalty_history/:id' => 'admin/historicals#loyalty_history', as: :member_loyalty_history
  get    'wallet_history/:id' => 'admin/historicals#wallet_history', as: :member_wallet_history
  get    'attendance_history/:id' => 'admin/historicals#attendance_history', as: :member_attendance_history
  get    'members/:id/edit' => 'admin/members#edit', as: :edit_member
  patch  'members/:id' => 'admin/members#update'
  get    'members/new' => 'admin/members#new', as: :new_member
  post   'members'     => 'admin/members#create'
  get    'members/:id'  => 'admin/members#image_capture', as: :image_page
  post   'members/upload_image' => 'admin/members#upload_image', as: :image_upload
  get    'members/activate_account/:id' => 'admin/members#activate_account', as: :activate_account
  patch  'members/activate_account/:id' => 'admin/members#complete_activation'
  get    'members/change_plan/:id' => 'admin/members#change_plan', as: :change_plan
  post   'send_paystack_invoice' => 'admin/members#send_paystack_invoice', as: :send_paystack_invoice
  patch  'members/change_plan/:id' => 'admin/members#change_plan_update'


  namespace :admin do
    resources :attendance_records, only: [:index]
    resources :subscription_plans
    resources :features
    resources :fitness_goals
    resources :payment_methods
    resources :member_steps
    resources :health_conditions
    post  'paystack_subscribe' => 'member_steps#paystack_subscribe', as: :paystack_subscription
    post  'upload_image' => 'member_steps#upload_image', as: :image_upload
    post  'member_check_in' => 'attendance_records#member_check_in', as: :member_check_in
    get   'developer_test_mail_form' => 'developer_test#get_mail_form', as: :get_mail_form
    patch 'developer_test_email' => 'developer_test#send_mail', as: :developer_send_mail
    post  'check_recurring' => 'subscription_plans#check_recurring', as: :check_recurring
    post  'check_selected_plan' => 'subscription_plans#check_selected_plan', as: :check_selected_plan
    resources :loyalties
    resources :one_off_revenues
  end

  post '/:paystack_webhook' => 'webhooks#receive', as: :receive_webhooks

  root 'welcome#index'

  get 'welcome/index'

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :start_date

  audited

  has_associated_audits

  include ImageUploader[:image]

  
    has_one  :account_detail, :dependent => :destroy
    accepts_nested_attributes_for :account_detail, update_only: true

    has_many :member_health_conditions
    has_many :pos_transactions
    accepts_nested_attributes_for :pos_transactions,
                                reject_if: :all_blank, allow_destroy: true

    has_many :cash_transactions
    accepts_nested_attributes_for :cash_transactions,
                                reject_if: :all_blank, allow_destroy: true

    has_many :health_conditions, through: :member_health_conditions

    has_many :loyalty_histories
    accepts_nested_attributes_for :loyalty_histories,
                                reject_if: :all_blank, allow_destroy: true

    has_many :subscription_histories
    accepts_nested_attributes_for :subscription_histories,
                                reject_if: :all_blank, allow_destroy: true

    has_many :pause_histories

    has_many :attendance_records

    has_one  :wallet_detail, :dependent => :destroy

    has_many  :wallet_histories

    has_many  :charges
    has_many  :paystack_charges
    
    belongs_to :fitness_goal
    belongs_to :payment_method
    belongs_to :subscription_plan

    validates_presence_of  :first_name, :last_name, :email
    # validates :email, :customer_code, uniqueness: true

    def fullname
      "#{first_name} #{last_name}"
    end

    scope :with_subscription_plan_id, (lambda {|subscription_plan_id|
      where(subscription_plan_id: [*subscription_plan_id])})
  
  scope :with_fitness_goal_id, (lambda {|fitness_goal_id|
      where(fitness_goal_id: [*fitness_goal_id])})
  
  scope :with_payment_method_id, (lambda {|payment_method_id|
      where(payment_method_id: [*payment_method_id])})
  
  scope :with_fitness_goal_name, (lambda {|fitness_goal_name|
      where('fitness_goals.goal_name = ?', fitness_goal_name).joins(:fitness_goal)
  })
  
  scope :with_payment_method_name, (lambda {|payment_method_name|
      where('payment_methods.payment_system = ?', payment_method_name).joins(:payment_method)
  })
  
  scope :with_subscription_plan_name, (lambda {|subscription_plan_name|
      where('subscription_plans.plan_name = ?', subscription_plan_name).joins(:subscription_plan)
  })
  
  scope :with_member_status, (lambda {|status|
      where('account_detail.member_status = ?', status).joins(:account_detail)
  })
  
  scope :sorted_by, (lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
      when /^created_at_/
        order("members.created_at #{direction}")
      when /^first_name/
        order("LOWER(members.first_name) #{direction}")
      when /^last_name/
        order("LOWER(members.last_name) #{direction}")
      when /^customer_code/
        order("members.customer_code #{direction}")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  })

  scope :created_at_gte, (lambda { |reference_time|
    where('members.created_at >= ?', reference_time)
  })


  scope :search_query, (lambda { |query|
    nil if query.blank?
    terms = []
    terms << query
    num_or_conditions = 2
    where(
        terms.map {
          or_clauses = [
              "members.customer_code = ?",
              "members.phone_number = ?",
          ].join(' OR ')
          "(#{ or_clauses })"
        }.join(' AND '),
        *terms.map { |e| [e] * num_or_conditions }.flatten
    ).joins(:subscription_plan)
  })

  scope :search_names, (lambda { |query|
    nil if query.blank?
    terms = query.to_s.downcase.split(/\s+/)
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    num_or_conditions = 2
    where(
        terms.map {
          or_clauses = [
              "LOWER(members.first_name) LIKE ?",
              "LOWER(members.last_name) LIKE ?"
          ].join(' OR ')
          "(#{ or_clauses })"
        }.join(' AND '),
        *terms.map { |e| [e] * num_or_conditions }.flatten
    ).joins(:subscription_plan)
  })


  def self.options_for_sorted_by
    [
        ['First Name (a-z)', 'first_name_asc'],
        ['Last Name (a-z)', 'last_name_asc' ],
        ['Created date (newest first)', 'created_at_desc'],
        ['Created Date (oldest first)', 'created_at_asc'],
        ['SubscriptionPlan (a-z)', 'plan_name_asc'],
        ['Customer Code', 'customer_code_asc' ],
    ]
  end

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :sorted_by,
      :search_query,
      :search_names,
      :with_subscription_plan_id,
      :with_fitness_goal_id,
      :with_payment_method_id,
      :with_created_at_gte,
      :with_member_status
    ]
  )

  def self.with_account_details
    Member.select('members.*, account_details.member_status as member_status, 
                    subscription_plans.plan_name as subscription_plan,
                    payment_methods.payment_system as payment_method').joins(:account_detail, :subscription_plan, :payment_method)
  end
    
end

app/helpers/admin/member_steps_helper.rb
module Admin::MemberStepsHelper
end

app/views/admin/member_steps/image_capture.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">New Member</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">Member</li>
                        <li class="breadcrumb-item active">Create Member</li>
                    </ol>
                </div>
                <div class="">
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>


            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div>
                <div class="row">
                    <div class="col-12">
                        </br>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Image Capture</h4>
                                <div class form-group id="image_upload-status">
                                </div>
                                <div id="my_camera">
                                </div>
                                <br/>
                                <div class="card-body">
                                    <input type=button value="Take Snapshot" onClick="take_snapshot()" class="btn btn-danger m-r-10">
                                    <%= link_to 'Skip if already taken', members_path, class: 'btn btn-info m-r-10' %>
                                </div>
                                <div id="results">
                        
                                </div>
                            </div>
                        </div>
                         <div class="card hide" id="image_capture-next">
                            <div class="card-body">
                                <%= link_to "Complete Registration", next_wizard_path , class: 'btn btn-danger m-r-10'%>
                            </div>
                        </div>
                        <div class="loader hide modal"></div>
                    </div>
                </div>
            </div>
        </div>

       

        


       

app/views/admin/member_steps/next_of_kin.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Nex of Kin</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">Member</li>
                        <li class="breadcrumb-item active">Nex of Kin</li>
                    </ol>
                </div>
                <div class="">
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>


            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div
                <div class="row">
                    <div class="col-12">
                        </br>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Create Next of Kin Details</h4>
                                <%= form_for([:admin, @member], url: wizard_path, html: {class: 'form-group m-t-40' }, method: :put) do |f| %> 
                                    <div class="form-group">
                                        <%= f.label :next_of_kin_name, 'Next of Kin Name' %>
                                        <%= f.text_field :next_of_kin_name, class: 'form-control form-control-line' %>
                                    </div>
                                     <div class="form-group">
                                        <%= f.label :next_of_kin_phone, 'Next of Kin Mobile' %>
                                        <%= f.number_field :next_of_kin_phone, class: 'form-control form-control-line' %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :next_of_kin_email, 'Next of Kin Email' %>
                                        <%= f.text_field :next_of_kin_email, class: 'form-control form-control-line' %>
                                    </div>
                                    <br/>

                                    <div>
                                        <%= link_to "Skip Step", next_wizard_path, class: 'btn btn-danger m-r-10'%>
                                        <%= f.submit 'Next', class: 'btn btn-danger m-r-10' %>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/admin/member_steps/payment.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Membership Payment</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">Member</li>
                        <li class="breadcrumb-item active">Receive Payment</li>
                    </ol>
                </div>
                <div class="">
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>


            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div>
                <div class="row">
                    <div class="col-12">            
                        <% if flash[:error] %>
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <%= flash[:notice] %>
                            </div>
                        <% elsif flash[:notice] %>
                            <div class="alert alert-success">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <%= flash[:notice] %>
                            </div>
                        <% end %>
                        </br>
                        <div class="card">
                            <div class form-group id="paystack-success">
                            </div>

                            <div class="loader hide modal"></div>
                  
                            <div class="card-body">
                                <h4 class="card-title" id="receive-payment">Receive Payment</h4>
                                <% if @member.payment_method.payment_system == "Debit Card" && @member.subscription_plan.recurring == true %>
                                    <div class="button-box m-t-20" id="remove-paystack-link">
                                        <button id="paystack-button" class="btn btn-info" href="#">Pay with Card Online</button>
                                    </div>
                                <% elsif @member.payment_method.payment_system == "POS Terminal" %>
                                    <div><h5>Amount to Charge: </h5><button class="btn btn-success" href="#">₦<%= @member.subscription_plan.cost %></button></div>
                                    <%= form_for([:admin, @member], url: wizard_path, method: :put) do |f| %>
                                        <%= f.fields_for :pos_transactions, PosTransaction.new do |transaction| %>
                                            <br/>
                                            <%= render 'postransaction_fields', f: transaction %>
                                        <% end %>
                                    <% end %>
                                <% elsif @member.payment_method.payment_system == "Debit Card" && @member.subscription_plan.recurring == false %>
                                    <div><h5>Amount to Charge: </h5><button class="btn btn-success" href="#">₦<%= @member.subscription_plan.cost %></button></div>
                                    <%= form_for([:admin, @member], url: wizard_path, method: :put) do |f| %>
                                        <%= f.fields_for :pos_transactions, PosTransaction.new do |transaction| %>
                                            <br/>
                                            <%= render 'postransaction_fields', f: transaction %>
                                        <% end %>
                                    <% end %>
                                <% elsif @member.payment_method.payment_system.titleize == "Cash" || @member.payment_method.payment_system.titleize == "Mobile Transfer"  %>
                                    <div><h5>Amount to Collect: </h5><button class="btn btn-success" href="#">₦<%= @member.subscription_plan.cost %></button></div>
                                    <%= form_for([:admin, @member], url: wizard_path, method: :put) do |f| %>
                                        <%= f.fields_for :cash_transactions, CashTransaction.new do |transaction| %>
                                            <br/>
                                            <%= render 'cashtransaction_fields', f: transaction %>
                                        <% end %>
                                    <% end %>
                                <% end %>

                            </div>
                        </div>
                        <div class="card remove-back-button">
                            <div class="card-body">
                                <%= link_to "Back", 'javascript:history.back()', class: 'btn btn-danger m-r-10'%>
                            </div>
                        </div>
                        <div class="card hide" id="reference-code">

                        </div>
                        <div class="card hide" id="manual-subscribe">
                            <div class="card-body">
                                <form>
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="manual-subscribe-reference" placeholder="Enter reference code displayed above!"> 
                                    </div>
                                    <button type="submit" class="btn btn-info" id="reference-submit">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>                   
                    <div class="card hide" id="payment-next">
                        <div class="card-body">
                            <%= link_to "Back", previous_wizard_path, class: 'btn btn-danger m-r-10'%>
                            <%= link_to "Proceed to Personal Profile", next_wizard_path , class: 'btn btn-success m-r-10'%>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        
        <%= content_for :after_body do %>
            <script src="https://js.paystack.co/v1/inline.js"></script>
        <% end %>

app/views/admin/member_steps/personal_profile.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Member Personal Profile</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">Member</li>
                        <li class="breadcrumb-item active">Create Member</li>
                    </ol>
                </div>
                <div class="">
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>


            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div
                <div class="row">
                    <div class="col-12">
                        </br>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Create Personal Profile</h4>
                                    <% if flash[:error] %>
                                        <div class="alert alert-danger">
                                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                            <%= flash[:notice] %>
                                        </div>
                                    <% elsif flash[:notice] %>
                                        <div class="alert alert-success">
                                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                            <%= flash[:notice] %>
                                        </div>
                                    <% end %>  
                                <%= form_for([:admin, @member], url: wizard_path, html: {class: 'form-group m-t-40' }, method: :put) do |f| %> 
                                     <div class="form-group">
                                        <%= f.label :phone_number, 'Phone Number' %>
                                        <%= f.number_field :phone_number, class: 'form-control form-control-line' %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :address, 'Address' %>
                                        <%= f.text_field :address, class: 'form-control form-control-line' %>
                                    </div>
                                    <div class="input-group">
                                        <%= f.text_field :date_of_birth, class:"form-control datepicker", "data-provide" => 'datepicker', placeholder:"Select Date of Birth" %>
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="icon-calender"></i></span>
                                        </div>
                                    </div>
                                    <br/>
                                    <div class="form-group">
                                        <%= f.label :health_condition_ids, 'Health Conditions' %>
                                        <%= f.select(:health_condition_ids, HealthCondition.all.pluck(:condition_name, :id), {}, { multiple: true, class: "health_selectize" }) %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :customer_code, 'Customer Code' %>
                                        <%= f.text_field :customer_code, class: 'form-control form-control-line' %>
                                    </div>
                                        <%= f.submit 'Next', class: 'btn btn-danger m-r-10' %>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>

                    <div id="add-contact" class="modal fade in health-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title" id="myModalLabel">Add Health Condition</h4> </div>
                                <div class="modal-body">
                                    <%= form_for([:admin, HealthCondition.new], html: {class: 'form-material m-t-40', id:"health_condition_form" }) do |f| %>
                                        <div class="form-group">
                                            <div class="col-md-12 m-b-20">
                                                <%= f.label :condition_name, 'Health Condition Name' %>
                                                <%= f.text_field :condition_name, class: 'form-control' %>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                             <%= f.submit 'Save', class: 'btn btn-info' %>
                                            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
                                        </div>
                                    <% end %>
                                </div> 
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                </div>
            </div>
        </div>
         <%= content_for :after_body do %>
            <script>
                // Date Picker
                jQuery('.mydatepicker, #datepicker').datepicker();
                jQuery('#datepicker-autoclose').datepicker({
                    autoclose: true,
                    todayHighlight: true
                });
                jQuery('#date-range').datepicker({
                    toggleActive: true
                });
                jQuery('#datepicker-inline').datepicker({
                    todayHighlight: true
                });
                // Daterange picker
                $('.input-daterange-datepicker').daterangepicker({
                    buttonClasses: ['btn', 'btn-sm'],
                    applyClass: 'btn-danger',
                    cancelClass: 'btn-inverse'
                });
                $('.input-daterange-timepicker').daterangepicker({
                    timePicker: true,
                    format: 'MM/DD/YYYY h:mm A',
                    timePickerIncrement: 30,
                    timePicker12Hour: true,
                    timePickerSeconds: false,
                    buttonClasses: ['btn', 'btn-sm'],
                    applyClass: 'btn-danger',
                    cancelClass: 'btn-inverse'
                });
                $('.input-limit-datepicker').daterangepicker({
                    format: 'MM/DD/YYYY',
                    minDate: '06/01/2015',
                    maxDate: '06/30/2015',
                    buttonClasses: ['btn', 'btn-sm'],
                    applyClass: 'btn-danger',
                    cancelClass: 'btn-inverse',
                    dateLimit: {
                        days: 6
                    }
                });
            </script>
        <% end %>
        
<% content_for :date do %>
  <script type="text/javascript">
    $(".datepicker").datetimepicker({
     format: "mm/dd/yyyy",
     autoclose: true,
    });

    $('.datepicker').on('changeDate', function(ev){
        $(this).datepicker('hide');
    });

  </script>
<% end %>