config/routes.rb
Rails.application.routes.draw do
  
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Plutus::Engine => "/plutus", :as => "plutus"
  
  # devise_for :members, :controllers => {:registrations => "admin/members"}
  devise_for :users,  :controllers => {:registrations => "admin/users"}
  

  devise_scope :user do
    get    'users' => 'admin/users#index', as: :users
    get    'user/:id' => 'admin/users#show', as: :user_profile
    get    'staff_tracking' => 'admin/users#staff_tracking', as: :staff_tracking
    get    'users/:id/edit' => 'admin/users#edit', as: :edit_user
    patch  'users/:id' =>               'admin/users#update'
    get    'change_role/:id/edit'  =>  'admin/users#change_role', as: :update_staff_role
    patch  'change_role/:id'  =>     'admin/users#update_role'
  end

  get    'members' => 'admin/members#index', as: :members
  get    'member/:id' => 'admin/members#show', as: :member_profile
  get    'renew_member/:id' => 'admin/members#renew_membership', as: :renew_member
  get    'unsubscribe_member/:id' => 'admin/members#unsubscribe_membership', as: :unsubscribe_member
  put    'cash_renewal/:id' => 'admin/members#cash_renewal', as: :cash_renewal
  put    'pos_renewal/:id' => 'admin/members#pos_renewal', as: :pos_renewal
  post   'paystack_renewal' => 'admin/members#paystack_renewal', as: :paystack_renewal
  post   'pause_subscription' => 'admin/members#pause_subscription', as: :pause_subscription
  post   'cancel_pause' => 'admin/members#cancel_pause', as: :cancel_pause
  get    'fund_wallet/:id' => 'admin/wallets#fund_page', as: :wallet_fund_page
  post   'paystack_wallet_fund' => 'admin/wallets#paystack_wallet_fund', as: :paystack_wallet_fund
  post   'wallet_renewal' => 'admin/members#wallet_renewal', as: :wallet_renewal
  put    'pos_wallet_fund/:id' => 'admin/wallets#pos_wallet_fund', as: :pos_wallet_fund
  put    'cash_wallet_fund/:id' => 'admin/wallets#cash_wallet_fund', as: :cash_wallet_fund
  get    'subscription_history/:id' => 'admin/historicals#subscription_history', as: :member_subscription_history
  get    'loyalty_history/:id' => 'admin/historicals#loyalty_history', as: :member_loyalty_history
  get    'wallet_history/:id' => 'admin/historicals#wallet_history', as: :member_wallet_history
  get    'attendance_history/:id' => 'admin/historicals#attendance_history', as: :member_attendance_history
  get    'members/:id/edit' => 'admin/members#edit', as: :edit_member
  patch  'members/:id' => 'admin/members#update'
  get    'members/new' => 'admin/members#new', as: :new_member
  post   'members'     => 'admin/members#create'
  get    'members/:id'  => 'admin/members#image_capture', as: :image_page
  post   'members/upload_image' => 'admin/members#upload_image', as: :image_upload
  get    'members/activate_account/:id' => 'admin/members#activate_account', as: :activate_account
  patch  'members/activate_account/:id' => 'admin/members#complete_activation'
  get    'members/change_plan/:id' => 'admin/members#change_plan', as: :change_plan
  post   'send_paystack_invoice' => 'admin/members#send_paystack_invoice', as: :send_paystack_invoice
  patch  'members/change_plan/:id' => 'admin/members#change_plan_update'


  namespace :admin do
    resources :attendance_records, only: [:index]
    resources :subscription_plans
    resources :features
    resources :fitness_goals
    resources :payment_methods
    resources :member_steps
    resources :health_conditions
    post  'paystack_subscribe' => 'member_steps#paystack_subscribe', as: :paystack_subscription
    post  'upload_image' => 'member_steps#upload_image', as: :image_upload
    post  'member_check_in' => 'attendance_records#member_check_in', as: :member_check_in
    get   'developer_test_mail_form' => 'developer_test#get_mail_form', as: :get_mail_form
    patch 'developer_test_email' => 'developer_test#send_mail', as: :developer_send_mail
    post  'check_recurring' => 'subscription_plans#check_recurring', as: :check_recurring
    post  'check_selected_plan' => 'subscription_plans#check_selected_plan', as: :check_selected_plan
    resources :loyalties
    resources :one_off_revenues
  end

  post '/:paystack_webhook' => 'webhooks#receive', as: :receive_webhooks

  root 'welcome#index'

  get 'welcome/index'

end

app/controllers/admin/wallets_controller.rb
class Admin::WalletsController < ApplicationController

   require 'accounting'

    # load_and_authorize_resource param_method: :wallet_member_params

    include Accounting

    before_action :authenticate_user!
    before_action :find_member

    before_action :get_paystack_object, only: [:paystack_wallet_fund]


   def fund_page
    gon.amount, gon.email, gon.firstName = @member.subscription_plan.cost * 100, @member.email, @member.first_name
    gon.lastName, gon.displayValue = @member.last_name, @member.phone_number
    gon.publicKey = ENV["PAYSTACK_PUBLIC_KEY"]
    gon.member_id = @member.id
   end


   def paystack_wallet_fund
        paystack_verify = verify_paystack_payment
        if paystack_verify["status"] == true && paystack_verify["data"]["status"] == "success"
            amount = (paystack_verify["data"]["amount"] / 100 ).to_i
            existing_balance = check_existing_balance
            new_balance = existing_balance + amount
            fund_method = 0
            update_wallet_detail(amount, existing_balance, new_balance)
            update_wallet_histories(amount, existing_balance, new_balance, fund_method)
            create_charge(amount,fund_method)
            options = {description: 'Wallet Funding', amount: amount}
            Accounting::Entry.new(options).card_entry    
            render status: 200, json: {
                message: "success"
            }
        else
            render status: 200, json: {
                message: "failed"
            }
        end
   end


   def pos_wallet_fund
      transaction_reference = wallet_member_params["pos_transactions_attributes"]["0"]["transaction_reference"]
      transaction_success_param = wallet_member_params["pos_transactions_attributes"]["0"]["transaction_success"]
      amount = wallet_member_params["pos_transactions_attributes"]["0"]["amount_received"].to_i
      transaction_success = true?(transaction_success_param)
      if !transaction_reference.nil? && transaction_success == true && amount.class == Integer
        existing_balance = check_existing_balance
        new_balance = existing_balance + amount
        fund_method = 1
        update_wallet_detail(amount, existing_balance, new_balance)
        update_wallet_histories(amount, existing_balance, new_balance, fund_method)
        create_pos_transaction(transaction_reference, transaction_success_param, amount)
        create_charge(amount,fund_method)
        options = {description: 'Wallet Funding', amount: amount}
        Accounting::Entry.new(options).card_entry
        redirect_to member_profile_path(@member)
      else
        flash[:notice] = "Check to ensure the right values are provided!"
        redirect_to wallet_fund_page_path(@member)
      end  
   end

   def cash_wallet_fund
        amount = wallet_member_params["cash_transactions_attributes"]["0"]["amount_received"].to_i
        if amount.class == Integer
            existing_balance = check_existing_balance
            new_balance = existing_balance + amount
            fund_method = 2
            update_wallet_detail(amount, existing_balance, new_balance)
            update_wallet_histories(amount, existing_balance, new_balance, fund_method)
            create_cash_transaction(amount)
            create_charge(amount,fund_method)
            options = {description: 'Wallet Funding', amount: amount}
            Accounting::Entry.new(options).cash_entry
            redirect_to member_profile_path(@member)
        else
            flash[:notice] = "Check to ensure the right values are provided!"
            redirect_to wallet_fund_page_path(@member)
        end  
   end



    private

    def create_charge(amount,fund_method)
        charge = @member.charges.new(service_plan: 'Funded Wallet',
                                    amount: amount,
                                    payment_method: fund_method,
                                    duration: '6 Months Wallet Expiration Period',
                                    gofit_transaction_id: SecureRandom.hex(4) 
                                    )
        if charge.save
            MemberMailer.wallet_funding(@member).deliver_later
        end
    end
   
    def true?(obj)
        obj.to_s == "true"
    end
    
    def find_member
        @member = Member.find(params[:id].to_i) 
    end

    def check_existing_balance
        balance = @member.wallet_detail ? @member.wallet_detail.current_balance : 0
    end

    def create_cash_transaction(cash_received)
        cash_transaction = @member.cash_transactions.create(
                                        amount_received: cash_received,
                                        cash_received_by: current_user.fullname,
                                        service_paid_for: "Funded Wallet",
                                        audit_comment: 'Funded wallet with cash'
        )
        return cash_transaction
    end


    def update_wallet_detail(amount, existing_balance, new_balance)
        total_funded = @member.wallet_detail.total_amount_funded ?  @member.wallet_detail.total_amount_funded : 0
        total_amount_used = @member.wallet_detail.total_amount_used ? @member.wallet_detail.total_amount_used : 0
        current_wallet_expiry_date = @member.wallet_detail.wallet_expiry_date.to_date ||= DateTime.now
        new_wallet_expiry_date = current_wallet_expiry_date + 180
        @member.wallet_detail.update(
            current_balance: new_balance,
            total_amount_funded: total_funded + amount,
            amount_last_funded: amount, 
            total_amount_used: total_amount_used,
            wallet_expiry_date: new_wallet_expiry_date,
            wallet_status: 0,
            date_last_funded: DateTime.now,
            audit_comment: "Member wallet funded"
        )
    end

    def create_pos_transaction(transaction_reference, transaction_success_param, amount)
        pos_transaction = @member.pos_transactions.create(
                                        amount_received: amount,
                                        transaction_success: transaction_success_param,
                                        transaction_reference: transaction_reference,
                                        processed_by: current_user.fullname,
                                        audit_comment: "Funded wallet via POS terminal" )
    end


    def update_wallet_histories(amount, existing_balance, new_balance, fund_method)
        @member.wallet_histories.create(
             amount_paid_in: amount,
             wallet_previous_balance: existing_balance,
             amount_used: 0,
             processed_by: current_user.fullname,
             wallet_new_balance: new_balance,
             wallet_fund_method: fund_method,
        )
    end


    def verify_paystack_payment
        reference = params[:reference_code].to_s
        transactions = PaystackTransactions.new(@paystackObj)
        result = transactions.verify(reference)
        return result
    end


    def get_paystack_object
        @paystackObj = Paystack.new
    end

    def wallet_member_params
        params.require(:member)
            .permit(
                    pos_transactions_attributes: [:transaction_success, :transaction_reference, :processed_by, :amount_received, :_destroy],
                    cash_transactions_attributes: [:amount_received, :cash_received_by, :service_paid_for, :_destroy]
            )
    end

end

app/helpers/admin/wallet_helper.rb
module Admin::WalletHelper
end

app/views/admin/wallets/_cashtransaction_fields.html.erb
<div class="form-group">
    <%= f.label :amount_received, 'Cash Received' %>
    <%= f.number_field :amount_received, class: 'form-control' %>
</div>
<div class="actions">
    <%= f.submit "Continue", class: 'btn btn-danger m-r-10' %>
</div>

app/views/admin/wallets/_postransaction_fields.html.erb
<div class="form-group">
    <%= f.label :amount_received, 'Amount Received' %>
    <%= f.number_field :amount_received, class: 'form-control form-control-line', placeholder: "Enter amount in numbers without comma" %>
</div>
<div class="form-group">
    <%= f.label :transaction_reference, 'Transaction Reference' %>
    <%= f.text_field :transaction_reference, class: 'form-control form-control-line', placeholder: "Enter POS Transaction reference number" %>
</div>
<div class="form-group">
    <%= f.label :transaction_success, 'Transaction Successesful?' %>
    <%= f.select(:transaction_success, options_for_select([['Yes', :true], ['No', :false]]), {include_blank: "Choose Yes or No"}, { :class =>  'form-control' } ) %>
</div>
<div class="actions">
    <%= f.submit "Continue", class: 'btn btn-danger m-r-10' %>
</div>

app/views/admin/wallets/fund_page.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Fund Wallet</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">Member</li>
                        <li class="breadcrumb-item active">Fund Wallet</li>
                    </ol>
                </div>
                <div class="">
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>


            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div
                <div class="row">
                    <div class="col-12">
                        <% flash.each do |key, value| %>
                            <div class="<%= flash_class(key) %>">
                                    <%= value %>
                            </div>
                        <% end %>
                        </br>
                        <div class="card">
                            
                            <div class form-group id="paystack_wallet_status">
                            </div>
                            

                            <div class="card-body">
                                 <button id="wallet-paystack-button" class="btn btn-success" href="#" value="<%= @member.id %>"> Pay with Card Online </button>
                                 <button id="wallet-cash-button" class="btn btn-info" href="#"> Pay with Cash </button>
                                 <button id="wallet-pos-button" class="btn btn-warning" href="#"> Pay with POS Terminal</button>
                            </div>

                            <div class="card-body hide" id="fund_wallet_pos_form">
                                <div><h5>Charge Using POS Terminal</h5></div>
                                <%= form_for([:admin, @member], url: pos_wallet_fund_path, method: :put, id: "pos_form") do |f| %>
                                    <%= f.fields_for :pos_transactions, PosTransaction.new do |transaction| %>
                                        <br/>
                                        <%= render 'postransaction_fields', f: transaction %>
                                    <% end %>
                                <% end %>
                            </div>

                            <div class="card-body hide" id="wallet_cash_form">
                                <div><h5>Amount Collected: </h5></div>
                                    <%= form_for([:admin, @member], url: cash_wallet_fund_path, method: :put) do |f| %>
                                        <%= f.fields_for :cash_transactions, CashTransaction.new do |transaction| %>
                                            <br/>
                                            <%= render 'cashtransaction_fields', f: transaction %>
                                        <% end %>
                                    <% end %>
                            </div>
                        </div>
                        <div class="card remove-back-button">
                            <div class="card-body">
                                <%= link_to "Back", member_profile_path(@member), class: 'btn btn-danger m-r-10'%>
                            </div>
                        </div>

                        <div class="card hide">

                        </div>

                        <div class="card hide">
                            <div class="card-body">
                                <form>
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="manual-subscribe-reference" placeholder="Enter reference code displayed above!"> 
                                    </div>
                                    <button type="submit" class="btn btn-info" id="reference-submit">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>  
                                 
                    <div class="card hide" id="access_profile">
                        <div class="card-body">
                            <%= link_to "Proceed to Member Profile", member_profile_path(@member) , class: 'btn btn-success m-r-10'%>
                        </div>
                    </div>
                    <div class="loader hide modal"></div>
                </div>

                <div id="wallet_amount_form" class="modal fade in feature-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h4 class="modal-title" id="myModalLabel">Enter Amount</h4> </div>
                            <div class="modal-body">
                                <form class='form-material m-t-40' id="form_reset">
                                    <div class="form-group">
                                        <div class="col-md-12 m-b-20">
                                            <input type="number" class="form-control" id="wallet_amount" placeholder="Enter Amount in Figures. e.g. 10000">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-info" id="pay_button" data-dismiss="modal">Pay</button>
                                        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
                                    </div>
                                <form>
                            </div> 
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
            </div>
        </div>
        
        <%= content_for :after_body do %>
            <script src="https://js.paystack.co/v1/inline.js"></script>
        <% end %>