config/routes.rb
Rails.application.routes.draw do
  
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Plutus::Engine => "/plutus", :as => "plutus"
  
  # devise_for :members, :controllers => {:registrations => "admin/members"}
  devise_for :users,  :controllers => {:registrations => "admin/users"}
  

  devise_scope :user do
    get    'users' => 'admin/users#index', as: :users
    get    'user/:id' => 'admin/users#show', as: :user_profile
    get    'staff_tracking' => 'admin/users#staff_tracking', as: :staff_tracking
    get    'users/:id/edit' => 'admin/users#edit', as: :edit_user
    patch  'users/:id' =>               'admin/users#update'
    get    'change_role/:id/edit'  =>  'admin/users#change_role', as: :update_staff_role
    patch  'change_role/:id'  =>     'admin/users#update_role'
  end

  get    'members' => 'admin/members#index', as: :members
  get    'member/:id' => 'admin/members#show', as: :member_profile
  get    'renew_member/:id' => 'admin/members#renew_membership', as: :renew_member
  get    'unsubscribe_member/:id' => 'admin/members#unsubscribe_membership', as: :unsubscribe_member
  put    'cash_renewal/:id' => 'admin/members#cash_renewal', as: :cash_renewal
  put    'pos_renewal/:id' => 'admin/members#pos_renewal', as: :pos_renewal
  post   'paystack_renewal' => 'admin/members#paystack_renewal', as: :paystack_renewal
  post   'pause_subscription' => 'admin/members#pause_subscription', as: :pause_subscription
  post   'cancel_pause' => 'admin/members#cancel_pause', as: :cancel_pause
  get    'fund_wallet/:id' => 'admin/wallets#fund_page', as: :wallet_fund_page
  post   'paystack_wallet_fund' => 'admin/wallets#paystack_wallet_fund', as: :paystack_wallet_fund
  post   'wallet_renewal' => 'admin/members#wallet_renewal', as: :wallet_renewal
  put    'pos_wallet_fund/:id' => 'admin/wallets#pos_wallet_fund', as: :pos_wallet_fund
  put    'cash_wallet_fund/:id' => 'admin/wallets#cash_wallet_fund', as: :cash_wallet_fund
  get    'subscription_history/:id' => 'admin/historicals#subscription_history', as: :member_subscription_history
  get    'loyalty_history/:id' => 'admin/historicals#loyalty_history', as: :member_loyalty_history
  get    'wallet_history/:id' => 'admin/historicals#wallet_history', as: :member_wallet_history
  get    'attendance_history/:id' => 'admin/historicals#attendance_history', as: :member_attendance_history
  get    'members/:id/edit' => 'admin/members#edit', as: :edit_member
  patch  'members/:id' => 'admin/members#update'
  get    'members/new' => 'admin/members#new', as: :new_member
  post   'members'     => 'admin/members#create'
  get    'members/:id'  => 'admin/members#image_capture', as: :image_page
  post   'members/upload_image' => 'admin/members#upload_image', as: :image_upload
  get    'members/activate_account/:id' => 'admin/members#activate_account', as: :activate_account
  patch  'members/activate_account/:id' => 'admin/members#complete_activation'
  get    'members/change_plan/:id' => 'admin/members#change_plan', as: :change_plan
  post   'send_paystack_invoice' => 'admin/members#send_paystack_invoice', as: :send_paystack_invoice
  patch  'members/change_plan/:id' => 'admin/members#change_plan_update'


  namespace :admin do
    resources :attendance_records, only: [:index]
    resources :subscription_plans
    resources :features
    resources :fitness_goals
    resources :payment_methods
    resources :member_steps
    resources :health_conditions
    post  'paystack_subscribe' => 'member_steps#paystack_subscribe', as: :paystack_subscription
    post  'upload_image' => 'member_steps#upload_image', as: :image_upload
    post  'member_check_in' => 'attendance_records#member_check_in', as: :member_check_in
    get   'developer_test_mail_form' => 'developer_test#get_mail_form', as: :get_mail_form
    patch 'developer_test_email' => 'developer_test#send_mail', as: :developer_send_mail
    post  'check_recurring' => 'subscription_plans#check_recurring', as: :check_recurring
    post  'check_selected_plan' => 'subscription_plans#check_selected_plan', as: :check_selected_plan
    resources :loyalties
    resources :one_off_revenues
  end

  post '/:paystack_webhook' => 'webhooks#receive', as: :receive_webhooks

  root 'welcome#index'

  get 'welcome/index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  audited
  has_many :login_activities, as: :user
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  enum role: [:manager, :supervisor, :officer, :guest]
  validates_presence_of  :first_name, :last_name, :encrypted_password, :email

  
  def fullname
    "#{first_name} #{last_name}"
  end

  scope :with_user_firstname, (lambda {|user_first_name|
    where('users.first_name = ?', user_first_name)})



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Devise::RegistrationsController
    
    load_and_authorize_resource param_method: :sign_up_params
    
    prepend_before_action :require_no_authentication, :only => [ :cancel]


    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end


    def new 
     super
    end

    def create
        build_resource(sign_up_params)
        if resource.save
          resource.audits
          redirect_to new_user_registration_path
          flash[:notice] = "User successfully created"
        else
          clean_up_passwords resource
          respond_with resource
        end
        resource.audits.last.user
    end

    def edit
        @user = User.find(params[:id])
    end

    def change_role
      @user = User.find(params[:id])
    end

    def update_role
      if @user.update(update_without_password_params)
        redirect_to user_profile_path(current_user)
        flash[:notice] = "User role successfully updated"     
      else
        render :change_role
      end
    end

    def update
        if update_without_password_params[:password].blank?
          resource_updated = resource.update_without_password(update_without_password_params)
          if resource_updated
            redirect_to users_path
            flash[:notice] = "Account successfully updated"
          else
            render :edit
          end
        elsif !update_with_password_params[:password].blank?
          resource_updated = User.update(update_without_password_params)
          if resource_updated
            bypass_sign_in(resource)
            redirect_to users_path
            flash[:notice] = "Account successfully updated"
          else
            flash[:error] = "Failed to Update record"
            render :edit
          end
        else
          render :edit
        end
      end

      def staff_tracking
        @user = User.new
        @users = User.all
      end



    private

    def sign_up_params
        params.require(:user)
            .permit(
                    :email,
                    :password,
                    :password_confirmation,
                    :first_name,
                    :last_name,
                    :role
            )
    end

    def update_without_password_params
        params.require(:user)
              .permit(
                    :email,
                    :first_name,
                    :last_name,
                    :password,
                    :password_confirmation,
                    :role
                   )
    end
    
    def update_with_password_params
      params.require(:user)
            .permit(
                    :email,
                    :password,
                    :password_confirmation,
                    :first_name,
                    :last_name,
                    :current_password,
                    :role
            )
    end
      


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/change_role.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Staff</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">Staff</li>
                        <li class="breadcrumb-item active">Edit Profile</li>
                    </ol>
                </div>
                <div class="">
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>


            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <%= flash[:notice] %>
                        </div>
                        </br>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Change Role</h4>
                                <%= form_for( @user, url: { controller: :users, action: :update_role },  html: {class: 'form-group m-t-40' }) do |f| %>
                                    <div class="form-group">
                                        <%= f.label :first_name, 'First Name' %>
                                        <%= f.text_field :first_name, class: 'form-control form-control-line' %>
                                    </div>
                                     <div class="form-group">
                                        <%= f.label :last_name, 'Last Name' %>
                                        <%= f.text_field :last_name, class: 'form-control form-control-line' %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :role, 'Staff Role' %>
                                        <%= f.select(:role, options_for_select(User.roles.keys.map { |role| [role.titleize, role]}), {include_blank: true}, { :class =>  "form-control" } ) %>
                                    </div>
                                    <div>
                                        <%= f.submit 'Update', class: 'btn btn-success m-r-10' %>
                                        <%= link_to 'Back', users_path, class: 'btn btn-danger m-r-10' %>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/admin/users/edit.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Staff</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">Staff</li>
                        <li class="breadcrumb-item active">Edit Profile</li>
                    </ol>
                </div>
                <div class="">
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>


            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <%= flash[:notice] %>
                        </div>
                        <br/>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Edit Profile</h4>
                                <%= form_for(@user, url: { controller: :users, action: :update },  html: {class: 'form-group m-t-40' }) do |f| %>
                                    <div class="form-group">
                                        <%= f.label :first_name, 'First Name' %>
                                        <%= f.text_field :first_name, class: 'form-control form-control-line' %>
                                    </div>
                                     <div class="form-group">
                                        <%= f.label :last_name, 'Last Name' %>
                                        <%= f.text_field :last_name, class: 'form-control form-control-line' %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :email, 'Email' %>
                                        <%= f.email_field :email, autofocus: true, class: 'form-control', id:'example-email2' %>
                                    </div>
                                    <div class="form-group">
                                         <%= f.label :password, 'Password' %>
                                        <%= f.password_field :password,  class: "form-control", autocomplete: "off" %>
                                    </div>
                                    <div class="form-group">
                                         <%= f.label :password_confirmation, "Password Confirmation" %>
                                        <%= f.password_field :password_confirmation,  class: "form-control", autocomplete: "off" %>
                                    </div>
                                    <div>
                                        <%= f.submit 'Update', class: 'btn btn-success m-r-10' %>
                                        <%= link_to 'Back', users_path, class: 'btn btn-danger m-r-10' %>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/admin/users/index.html.erb
        
        <div class="page-wrapper">
                    <!-- ============================================================== -->
                    <!-- Bread crumb and right sidebar toggle -->
                    <!-- ============================================================== -->
                    <div class="row page-titles">
                        <div class="col-md-5 align-self-center">
                            <h3 class="text-themecolor">Staff Credentials</h3>
                        </div>
                        <div class="col-md-7 align-self-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                <li class="breadcrumb-item">Staff</li>
                                <li class="breadcrumb-item active">All Staff</li>
                            </ol>
                        </div>
                        <div>
                            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                        </div>
                    </div>
                    <!-- ============================================================== -->
                    <!-- End Bread crumb and right sidebar toggle -->
                    <!-- ============================================================== -->
                    <!-- ============================================================== -->
                    <!-- Container fluid  -->
                    <!-- ============================================================== -->
                    <div class="container-fluid">
                        <!-- ============================================================== -->
                        <!-- Start Page Content -->
                        <!-- ============================================================== -->
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="card-title">Staff List</h4>
                                        <h6 class="card-subtitle"></h6>
                                        <div class="table-responsive">
                                            <table id="demo-foo-addrow" class="table m-t-30 table-hover contact-list" data-page-size="10">
                                                <thead>
                                                    <tr>
                                                        <th>ID</th>
                                                        <th>Full Name</th>
                                                        <th>Email</th>
                                                        <th>Role</th>
                                                        <th></th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <% @users.each do |user| %>
                                                    <tr>
                                                        <td><%= user.id %></td>
                                                        <td>
                                                            <%= image_tag( "users/person.png", alt: "user", size:"40", class:"img-circle" ) %><%= link_to "#{user.fullname}" %>
                                                        </td>
                                                        <td><%= user.email %></td>
                                                        <td><span class="label label-danger"><%= user.role %></span> </td>
                                                        <td>
                                                            <%= link_to "View Profile", user_profile_path(user), class:"btn btn-info btn-rounded" %>
                                                        </td>
                                                        <td>
                                                             <%= link_to 'Edit Profile',  edit_user_path(user), class:"btn btn-info btn-rounded" %>
                                                        </td>
                                                    </tr>
                                                <% end %>
                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <td colspan="2">
                                                            <%= link_to "Add New Staff", new_user_registration_path, class:"btn btn-info btn-rounded" %>                                                   
                                                        </td>                                               
                                                                <!-- /.modal-content -->
                                                            </div>
                                                            <!-- /.modal-dialog -->
                                                        </div>
                                                        <td colspan="7">
                                                            <div class="text-right">
                                                                <ul class="pagination"> </ul>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

app/views/admin/users/new.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Staff</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">Staff</li>
                        <li class="breadcrumb-item active">Create Staff</li>
                    </ol>
                </div>
                <div class="">
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>


            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <%= flash[:notice] %>
                        </div>
                        </br>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Create New Staff</h4>
                                <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'form-material m-t-40' }) do |f| %>
                                    <div class="form-group">
                                        <%= f.label :first_name, 'First Name' %>
                                        <label>First Name <span class="help"> e.g. "John"</span></label>
                                        <%= f.text_field :first_name, class: 'form-control form-control-line', placeholder: "Enter First Name here..." %>
                                    </div>
                                     <div class="form-group">
                                        <%= f.label :last_name, 'Last Name' %>
                                        <%= f.text_field :last_name, class: 'form-control form-control-line', placeholder: "Enter Last Name here..." %>
                                    </div>
                                    <div class="form-group">
                                        <label for="example-email">Email <span class="help"> e.g. "example@gmail.com"</span></label>
                                        <%= f.email_field :email, autofocus: true, class: 'form-control', id:'example-email2', placeholder: "Email" %>
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <%= f.password_field :password,  class: "form-control", placeholder: "Password", autocomplete: "off" %>
                                    </div>
                                    <div class="form-group">
                                        <label>Password Confirmation</label>
                                        <%= f.password_field :password_confirmation,  class: "form-control", placeholder: "Password Confirmation", autocomplete: "off" %>
                                    </div>
                                    <div class="form-group">
                                        <%= f.label :role, 'Staff Role' %>
                                        <label>Staff Role</label></br>
                                        <%= f.select(:role, options_for_select(User.roles.keys.map { |role| [role.titleize, role]}), {include_blank: true}, { :class =>  "form-control" } ) %>
                                    </div>
                                    <div>
                                        <%= f.submit 'Create', class: 'btn btn-danger m-r-10' %>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/admin/users/show.html.erb
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-themecolor">Profile</h3>
                </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item">pages</li>
                        <li class="breadcrumb-item active">Profile</li>
                    </ol>
                </div>
                <div>
                    <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <!-- Row -->
                <div class="row">
                    <!-- Column -->
                    <div class="col-lg-4 col-xlg-3 col-md-5">
                        <div class="card">
                            <div class="card-body">
                                <center class="m-t-30"><%= image_tag( "users/5.png", alt: "user", size:"150", class:"img-circle" ) %>
                                    <h4 class="card-title m-t-10"><%= @user.fullname %></h4>
                                    <h6 class="card-subtitle"><%= @user.role %></h6>
                                    <div class="row text-center justify-content-md-center">
                                    </div>
                                </center>
                            </div>
                            <div>
                                <hr> </div>
                            <div class="card-body"> <small class="text-muted">Email address </small>
                                <h6><%= @user.email %></h6> <small class="text-muted p-t-30 db">Phone</small>
                                <h6>+91 654 784 547</h6> <small class="text-muted p-t-30 db">Address</small>
                                <h6>71 Pilgrim Avenue Chevy Chase, MD 20815</h6>
                                <hr/>
                                 <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-info m-r-10' %>
                                 <%= link_to 'Change Role', update_staff_role_path(@user), class: 'btn btn-info m-r-10' %>
                                <br/>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <!-- Column -->
                   
            </div>
        </div>